settings:
  index:
    # single node, no sharding
    number_of_shards: 3
    number_of_replicas: 1
mappings:
    dynamic: false # disable dynamic mapping
    properties:
      id:
        type: integer
      name: &fr_text
        type: text
        analyzer: french
      description: *fr_text