settings:
  index:
    # single node, no sharding
    number_of_shards: 2
    number_of_replicas: 1
mappings:
  dynamic: false # disable dynamic mapping
  properties:
    name: &fr_text
      type: text
      analyzer: french
    description: *fr_text
    pattern: *fr_text